config/routes.rb
Rails.application.routes.draw do
  resources :admissions
  resources :patients
  resources :diagnoses
  resources :diagnostic_procedures
  resources :order_frequencies
  resources :treatments
  resources :medication_orders
  resources :allergies
  resources :observations
  resources :symptoms
  resources :facilities
  resources :chronic_conditions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "patients#list"
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all.order(created_at: :desc)
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to treatments_url, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to treatments_url, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:patient_id, :description, :necessity)
    end
end

app/views/treatments/_form.html.erb
<%= form_with(model: treatment, local: true) do |form| %>
    <div class="row">
      <div class="col-md-6 mb-4">
        <div class="card">
          <header class="card-header">
            <h2 class="h3 card-header-title"> Treatment
              <%= link_to 'Back', treatments_path,class: "float-right" %>
            </h2>
          </header>

          <div class="card-body">
            <% if treatment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

                  <ul>
                    <% treatment.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="form-group mb-4">
              <%= form.label :description %>
              <%= form.text_area :description, id: :treatment_description, class:"form-control" %>
            </div>

            <div class="form-group mb-4">
              <%= form.label :necessity %>
              <%= form.text_area :necessity, id: :treatment_necessity, class:"form-control" %>
            </div>

            <div class="actions text-center w-100">
              <%= form.submit class:"btn btn-primary" %>
            </div>

          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form', treatment: @treatment %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-4">
  <header class="card-header">
    <h2 class="h3 card-header-title">Treatments <%= link_to 'New Treatment', new_treatment_path, class: "btn btn-sm btn-primary float-right" %></h2>
  </header>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Description</th>
          <th>Necessity</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
          <% @treatments.each do |treatment| %>
            <tr>
              <td><%= treatment.description %></td>
              <td><%= treatment.necessity %></td>
              <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
              <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form', treatment: @treatment %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Description:</strong>
  <%= @treatment.description %>
</p>

<p>
  <strong>Necessity:</strong>
  <%= @treatment.necessity %>
</p>

<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>