config/routes.rb
Rails.application.routes.draw do
  resources :admissions
  resources :patients
  resources :diagnoses
  resources :diagnostic_procedures
  resources :order_frequencies
  resources :treatments
  resources :medication_orders
  resources :allergies
  resources :observations
  resources :symptoms
  resources :facilities
  resources :chronic_conditions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "patients#list"
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  has_many :medication_orders, foreign_key: :frequency_id

  enum unit: {Hour: 0}
end

app/controllers/order_frequencies_controller.rb
class OrderFrequenciesController < ApplicationController
  before_action :set_order_frequency, only: [:show, :edit, :update, :destroy]

  # GET /order_frequencies
  # GET /order_frequencies.json
  def index
    @order_frequencies = OrderFrequency.all.order(created_at: :desc)
  end

  # GET /order_frequencies/1
  # GET /order_frequencies/1.json
  def show
  end

  # GET /order_frequencies/new
  def new
    @order_frequency = OrderFrequency.new
  end

  # GET /order_frequencies/1/edit
  def edit
  end

  # POST /order_frequencies
  # POST /order_frequencies.json
  def create
    @order_frequency = OrderFrequency.new(order_frequency_params)

    respond_to do |format|
      if @order_frequency.save
        format.html { redirect_to order_frequencies_url, notice: 'Order frequency was successfully created.' }
        format.json { render :show, status: :created, location: @order_frequency }
      else
        format.html { render :new }
        format.json { render json: @order_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_frequencies/1
  # PATCH/PUT /order_frequencies/1.json
  def update
    respond_to do |format|
      if @order_frequency.update(order_frequency_params)
        format.html { redirect_to order_frequencies_url, notice: 'Order frequency was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_frequency }
      else
        format.html { render :edit }
        format.json { render json: @order_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_frequencies/1
  # DELETE /order_frequencies/1.json
  def destroy
    @order_frequency.destroy
    respond_to do |format|
      format.html { redirect_to order_frequencies_url, notice: 'Order frequency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_frequency
      @order_frequency = OrderFrequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_frequency_params
      params.require(:order_frequency).permit(:value, :unit)
    end
end

app/views/order_frequencies/_form.html.erb
<%= form_with(model: order_frequency, local: true) do |form| %>
    <div class="col-md-6 mb-4">
      <div class="card">
        <header class="card-header">
          <h2 class="h3 card-header-title"> Order Frequency
            <%= link_to 'Back', order_frequencies_path,class: "float-right" %>
          </h2>
        </header>
        <div class="card-body">
          <% if order_frequency.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(order_frequency.errors.count, "error") %> prohibited this order_frequency from being saved:</h2>

                <ul>
                  <% order_frequency.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group mb-4">
            <%= form.label :value %>
            <%= form.text_field :value, id: :order_frequency_value , class:"form-control"%>
          </div>

          <div class="form-group mb-4">
            <%= form.label :unit %>
            <%= form.select :unit, OrderFrequency.units.map{|u| [u[0].humanize, u[0]]},{}, class:"form-control"  %>
          </div>
          <div class="actions text-center w-100">
            <%= form.submit class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/order_frequencies/edit.html.erb
<%= render 'form', order_frequency: @order_frequency %>

app/views/order_frequencies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-4">
  <header class="card-header">
    <h2 class="h3 card-header-title">Medication Orders <%= link_to 'New Order Frequency', new_order_frequency_path, class: "btn btn-sm btn-primary float-right" %></h2>
  </header>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Value</th>
          <th>Unit</th>
          <th colspan="2"></th>
        </tr>
        </thead>

        <tbody>
        <% @order_frequencies.each do |order_frequency| %>
            <tr>
              <td><%= order_frequency.value %></td>
              <td><%= order_frequency.unit %></td>
              <td><%= link_to 'Edit', edit_order_frequency_path(order_frequency) %></td>
              <td><%= link_to 'Destroy', order_frequency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/order_frequencies/new.html.erb
<%= render 'form', order_frequency: @order_frequency %>

app/views/order_frequencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @order_frequency.value %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @order_frequency.unit %>
</p>

<%= link_to 'Edit', edit_order_frequency_path(@order_frequency) %> |
<%= link_to 'Back', order_frequencies_path %>