config/routes.rb
Rails.application.routes.draw do
  resources :admissions
  resources :patients
  resources :diagnoses
  resources :diagnostic_procedures
  resources :order_frequencies
  resources :treatments
  resources :medication_orders
  resources :allergies
  resources :observations
  resources :symptoms
  resources :facilities
  resources :chronic_conditions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "patients#list"
end

app/models/admission.rb
class Admission < ApplicationRecord
  has_many :admission_observations
  has_many :observations, through: :admission_observations

  has_many :admission_symptoms
  has_many :symptoms, through: :admission_symptoms

  has_many :admission_diagnoses
  has_many :diagnoses, through: :admission_diagnoses

end

app/models/admission_diagnosis.rb
class AdmissionDiagnosis < ApplicationRecord
  belongs_to :admission, optional: true
  belongs_to :diagnosis, optional: true
end

app/models/admission_observation.rb
class AdmissionObservation < ApplicationRecord
  belongs_to :admission, optional: true
  belongs_to :observation, optional: true
end

app/models/admission_symptom.rb
class AdmissionSymptom < ApplicationRecord
  belongs_to :admission, optional: true
  belongs_to :symptom, optional: true
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chronic_condition.rb
class ChronicCondition < Diagnosis
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  belongs_to :order_frequency, foreign_key: :frequency_id

  enum unit: {MG: 0}
  enum route: {PO: 0, IM: 1, SC: 2}
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :admission
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  has_many :medication_orders, foreign_key: :frequency_id

  enum unit: {Hour: 0}
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :admission

  has_many :patient_allergies
  has_many :allergies, through: :patient_allergies

  has_many :patient_medication_orders
  has_many :medication_orders, through: :patient_medication_orders

  has_many :patient_diagnostic_procedures
  has_many :diagnostic_procedures, through: :patient_diagnostic_procedures

  has_many :patient_treatments
  has_many :treatments, through: :patient_treatments

  has_many :patient_diagnoses
  has_many :diagnoses, through: :patient_diagnoses

  has_many :patient_chronic_conditions
  has_many :chronic_conditions, through: :patient_chronic_conditions

  enum gender: {Male: 0, Female: 1, Other: 2}

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def age
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/models/patient_allergy.rb
class PatientAllergy < ApplicationRecord
  belongs_to :patient, optional: true
  belongs_to :allergy, optional: true
end

app/models/patient_diagnosis.rb
class PatientDiagnosis < ApplicationRecord
  belongs_to :patient, optional: true
  belongs_to :diagnosis, optional: true
end

app/models/patient_treatment.rb
class PatientTreatment < ApplicationRecord
  belongs_to :patient, optional: true
  belongs_to :treatment, optional: true
end

app/models/symptom.rb
class Symptom < ApplicationRecord
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper

  def medication_orders(patient)
    patient.medication_orders.each_with_object([]) do |e, r|
      r << "#{e.name} #{e.dosage} #{e.route} #{e.order_frequency.value}"
    end.join(', ')
  end

  def bootstrap_class_for flash_type
    case flash_type.to_sym
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-info"
      when :notice
        "alert-success"
      else
        flash_type.to_s
    end
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="u-footer d-md-flex align-items-md-center text-center text-md-left text-muted text-muted">
  <p class="h5 mb-0 ml-auto">
    &copy; 2019 <a class="link-muted" href="https://htmlstream.com/" target="_blank">Saint Bernard</a>. All Rights Reserved.
  </p>
</footer>
<!-- End Footer -->

app/views/shared/_header.html.erb
<!-- Header (Topbar) -->
<header class="u-header">
  <div class="u-header-left">
    <%= link_to root_path, class: "u-header-logo u-header-logo h1 m-0 text-primary" do %>
     Saint Bernard
    <% end %>
  </div>
  <div class="u-header-right">
    <%= link_to root_path, class: "m-0 text-primary" do %>
        <i class="fas fa-long-arrow-alt-left"></i> Back
    <% end %>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<aside id="sidebar" class="u-sidebar">
  <div class="u-sidebar-inner">
    <header class="u-sidebar-header">
      <%= link_to root_path(locale: I18n.locale), class: "u-sidebar-logo u-header-logo h1 m-0 text-primary" do %>
          CMS Builder
      <% end %>
    </header>
    <nav class="u-sidebar-nav">
      <ul class="u-sidebar-nav-menu u-sidebar-nav-menu--top-level side-bar" >
        <!-- Dashboard -->
        <li class="u-sidebar-nav-menu__item">
          <%= link_to admissions_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas"></i>
              <i class="fas  fa-user-plus u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Admission
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to patients_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-user-injured u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Patient
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to diagnoses_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-diagnoses u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  diagnosis
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to diagnostic_procedures_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-diagnoses u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Diagnostic Procedure
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to order_frequencies_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-sort u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Order Frequency
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to treatments_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-plus u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Treatment
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to medication_orders_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-prescription u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Medication Order
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to allergies_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-allergies u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Allergy
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to observations_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fas fa-microscope u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Observation
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to symptoms_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fa fa-cubes u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Symptom
              </span>
          <%end%>
        </li>
        <li class="u-sidebar-nav-menu__item">
          <%= link_to facilities_path, class:"u-sidebar-nav-menu__link"  do%>
              <i class="fa fa-cubes u-sidebar-nav-menu__item-icon"></i>
              <span class="u-sidebar-nav-menu__item-title">
                  Facility
              </span>
          <%end%>
        </li>
        <!-- End Dashboard -->
      </ul>
    </nav>
  </div>
</aside>
<!-- End Sidebar -->