config/routes.rb
Rails.application.routes.draw do
  resources :admissions
  resources :patients
  resources :diagnoses
  resources :diagnostic_procedures
  resources :order_frequencies
  resources :treatments
  resources :medication_orders
  resources :allergies
  resources :observations
  resources :symptoms
  resources :facilities
  resources :chronic_conditions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "patients#list"
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  before_action :set_allergy, only: [:show, :edit, :update, :destroy]

  # GET /allergies
  # GET /allergies.json
  def index
    @allergies = Allergy.all.order(created_at: :desc)
  end

  # GET /allergies/1
  # GET /allergies/1.json
  def show
  end

  # GET /allergies/new
  def new
    @allergy = Allergy.new
  end

  # GET /allergies/1/edit
  def edit
  end

  # POST /allergies
  # POST /allergies.json
  def create
    @allergy = Allergy.new(allergy_params)

    respond_to do |format|
      if @allergy.save
        format.html { redirect_to allergies_url, notice: 'Allergy was successfully created.' }
        format.json { render :show, status: :created, location: @allergy }
      else
        format.html { render :new }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allergies/1
  # PATCH/PUT /allergies/1.json
  def update
    respond_to do |format|
      if @allergy.update(allergy_params)
        format.html { redirect_to allergies_url, notice: 'Allergy was successfully updated.' }
        format.json { render :show, status: :ok, location: @allergy }
      else
        format.html { render :edit }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allergies/1
  # DELETE /allergies/1.json
  def destroy
    @allergy.destroy
    respond_to do |format|
      format.html { redirect_to allergies_url, notice: 'Allergy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allergy
      @allergy = Allergy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allergy_params
      params.require(:allergy).permit(:patient_id, :description)
    end
end

app/views/allergies/_form.html.erb
<%= form_with(model: allergy, local: true) do |form| %>
    <div class="col-md-6 mb-4">
      <div class="card">
        <header class="card-header">
          <h2 class="h3 card-header-title"> Allergy
            <%= link_to 'Back', allergies_path,class: "float-right" %>
          </h2>
        </header>
        <div class="card-body">
          <% if allergy.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(allergy.errors.count, "error") %> prohibited this allergy from being saved:</h2>

                <ul>
                  <% allergy.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group mb-4">
            <%= form.label :description %>
            <%= form.text_area :description, id: :allergy_description, class:"form-control" %>
          </div>
          <div class="actions text-center w-100">
            <%= form.submit class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/allergies/edit.html.erb
<%= render 'form', allergy: @allergy %>

app/views/allergies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-4">
  <header class="card-header">
    <h2 class="h3 card-header-title">Allergies <%= link_to 'New Admission', new_allergy_path, class: "btn btn-sm btn-primary float-right" %></h2>
  </header>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Description</th>
          <th colspan="2"></th>
        </tr>
        </thead>

        <tbody>
        <% @allergies.each do |allergy| %>
            <tr>
              <td><%= allergy.description %></td>
              <td><%= link_to 'Edit', edit_allergy_path(allergy) %></td>
              <td><%= link_to 'Destroy', allergy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/allergies/new.html.erb
<%= render 'form', allergy: @allergy %>

app/views/allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @allergy.patient %>
</p>

<p>
  <strong>Description:</strong>
  <%= @allergy.description %>
</p>

<%= link_to 'Edit', edit_allergy_path(@allergy) %> |
<%= link_to 'Back', allergies_path %>